# STATUS: DRAFT - UNVERIFIED - requires human review at Gate G2
"""G2 block diagram (light + dark PNG, plus the .dot source in review/G2/).

  python3 tools/viz/blockdiagram.py        (needs Graphviz `dot`)

Reflects the G2 schematics (hardware/*/design/*.py). Licence: MIT.
"""
import pathlib
import subprocess

REPO = pathlib.Path(__file__).resolve().parents[2]

THEMES = {
    "light": dict(bg="#ffffff", ink="#0b0b0b", ink2="#52514e", node="#f4f6f8", line="#9aa3ad", power="#c26a00",
                  c_pwr="#fff4e5", c_fc="#eaf2fc", c_esc="#f5ecfa", c_sat="#e9f6ee", b_pwr="#d08a2a", b_fc="#2a78d6",
                  b_esc="#8e44ad", b_sat="#1baf7a", hi="#ffffff"),
    "dark": dict(bg="#0e1116", ink="#f0f2f5", ink2="#b8bec7", node="#1d232d", line="#6b7480", power="#f0a040",
                 c_pwr="#2a2116", c_fc="#16202e", c_esc="#231a2b", c_sat="#15251c", b_pwr="#c88a3a", b_fc="#5a9be6",
                 b_esc="#b07ad0", b_sat="#3fbf8a", hi="#2a313d"),
}

DOT = r"""// STATUS: DRAFT - UNVERIFIED - requires human review at Gate G2
// MicroScout G2 block diagram (generated by tools/viz/blockdiagram.py from this template)
digraph microscout_g2 {
  graph [rankdir=TB, bgcolor="{bg}", fontname="Inter", fontsize=13, fontcolor="{ink}", nodesep=0.3, ranksep=0.45,
         pad=0.3, newrank=true, label="MicroScout - G2 schematic architecture (DRAFT - UNVERIFIED)", labelloc=t];
  node  [shape=box, style="rounded,filled", fillcolor="{node}", color="{line}", fontname="Inter", fontsize=11, fontcolor="{ink}", penwidth=1.2, margin="0.12,0.06"];
  edge  [color="{line}", fontname="Inter", fontsize=9, fontcolor="{ink2}", arrowsize=0.7, penwidth=1.1];

  subgraph cluster_pwr {
    label="Power  (flight-controller board)"; style="rounded,filled"; fillcolor="{c_pwr}"; color="{b_pwr}"; fontcolor="{ink}"; fontsize=12;
    BAT  [label="2S LiHV 550 mAh\nXT30 + balance lead", fillcolor="{hi}", penwidth=2, color="{power}"];
    USB  [label="USB-C\n+ USBLC6 ESD"];
    SNS  [label="1 mΩ shunt\n+ INA226"];
    CHG  [label="BQ25887\n2S charger + balancing"];
    OR   [label="VLOGIC\nSS34 diode-OR"];
    SW   [label="LTC2954 soft switch\n+ TLV6700 low-battery cut-off"];
    B33  [label="TPS62162\n3.3 V"];
    B5   [label="TPS62133\n5 V"];
    DRV  [label="TPS22810 switch\n+ MT3608 → 9.6 V"];
    {rank=same; USB; BAT;}
    {rank=same; CHG; SNS;}
    {rank=same; OR; SW;}
  }

  subgraph cluster_fc {
    label="Flight controller (40 mm)"; style="rounded,filled"; fillcolor="{c_fc}"; color="{b_fc}"; fontcolor="{ink}"; fontsize=12;
    MCU  [label="ESP32-S3-WROOM-1\nflight control · Wi-Fi · BLE · camera stream", fillcolor="{hi}", penwidth=2, color="{b_fc}", fontsize=12];
    IMU  [label="ICM-42688-P IMU\nSPI, 8 kHz"];
    FLOW [label="Flow deck v2\nflow + down ToF"];
    I2C  [label="I²C sensors\nBMP388 · QMC5883P · 2× TCA6408A"];
    CAM  [label="OV2640 camera\n2.8 V / 1.2 V LDOs"];
    RX   [label="ExpressLRS\nreceiver"];
    LED  [label="4× WS2812B\n+ buzzer"];
  }

  subgraph cluster_sat {
    label="ToF satellites"; style="rounded,filled"; fillcolor="{c_sat}"; color="{b_sat}"; fontcolor="{ink}"; fontsize=12;
    TOF  [label="3× VL53L1X (sides, rear)\n1× VL53L5CX 8×8 (front)"];
  }

  subgraph cluster_esc {
    label="4-in-1 ESC (30 mm, AM32)"; style="rounded,filled"; fillcolor="{c_esc}"; color="{b_esc}"; fontcolor="{ink}"; fontsize=12;
    ESC  [label="4× AT32F421 + FD6288Q\n24× 30 V MOSFETs", fillcolor="{hi}", penwidth=2, color="{b_esc}"];
    E33  [label="TPS62162\n3.3 V for the MCUs"];
    MOT  [label="4× EX1103 11000KV\n2-inch props in ducts"];
  }

  LEG [shape=plaintext, style="", fontsize=12, fontcolor="{ink2}",
       label="Legend\l━━  power (thick = battery current)\l- - -  USB-only logic supply\l──  data / control\lNothing here is built or tested.\l"];
  {rank=same; LEG; USB;}

  // power paths
  BAT -> SNS [color="{power}", penwidth=2.4];
  USB -> CHG [color="{power}", label="5 V"];
  CHG -> BAT [color="{power}", label="charge"];
  SNS -> OR  [color="{power}"];
  USB -> OR  [color="{power}", style=dashed];
  OR  -> SW  [color="{power}", constraint=false];
  SW  -> B33 [color="{power}", label="EN"];
  SW  -> B5  [color="{power}", label="EN"];
  SW  -> DRV [color="{power}", label="EN"];
  SNS -> ESC [color="{power}", penwidth=2.4, label="battery (always connected)"];
  DRV -> ESC [color="{power}", label="9.6 V drivers"];
  DRV -> E33 [color="{power}"];
  E33 -> ESC [color="{power}"];
  ESC -> MOT [color="{power}", penwidth=2.4, label="3-phase"];
  B33 -> MCU [color="{power}", label="3.3 V"];
  B5  -> RX  [color="{power}", label="5 V"];

  // signals
  MCU -> IMU  [dir=both, label="SPI"];
  MCU -> FLOW [dir=both, label="SPI + I²C"];
  MCU -> I2C  [dir=both, label="I²C 400 kHz"];
  MCU -> TOF  [dir=both, label="I²C"];
  MCU -> CAM  [dir=both, label="DVP + SCCB"];
  MCU -> RX   [dir=both, label="CRSF"];
  MCU -> LED  [label="SPI3 data"];
  MCU -> ESC  [dir=both, label="4× bidirectional DShot"];
}
"""


def main():
    g2 = REPO / "review" / "G2"
    g2.mkdir(parents=True, exist_ok=True)
    for name, t in THEMES.items():
        src = DOT
        for k, v in t.items():
            src = src.replace("{" + k + "}", v)
        if name == "light":
            (g2 / "block-diagram.dot").write_text(src)
        out = REPO / "docs" / "figures" / f"block-diagram-{name}.png"
        subprocess.run(["dot", "-Tpng", "-Gdpi=170", "-o", str(out)], input=src.encode(), check=True)
        if name == "light":
            subprocess.run(["dot", "-Tsvg", "-o", str(g2 / "block-diagram.svg")], input=src.encode(), check=True)
        print("wrote", out.relative_to(REPO))


if __name__ == "__main__":
    main()
