# STATUS: DRAFT - UNVERIFIED - requires human review at Gate G2
# SPDX-License-Identifier: MIT
"""Shared colours, fonts and data loading for MicroScout figures and animations.

Palette: the dataviz reference palette (categorical slots 1-7, light and dark
steps). Validated with the skill's validate_palette.js on 2026-10-05:
slots 1-3 pass all-pairs; slots 1-7 pass adjacent pairs; slots 3/4/5 are below
3:1 contrast on the light surface, so every chart that uses them carries
visible direct labels.
"""
import csv
import importlib.util
import pathlib

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402

REPO = pathlib.Path(__file__).resolve().parents[2]
FIG_DIR = REPO / "docs" / "figures"
ANIM_DIR = FIG_DIR / "anim"

THEMES = {
    "light": dict(
        surface="#fcfcfb", page="#f9f9f7", ink="#0b0b0b", ink2="#52514e", muted="#898781",
        grid="#e1e0d9", axis="#c3c2b7", warn="#d03b3b",
        series=["#2a78d6", "#eb6834", "#1baf7a", "#eda100", "#e87ba4", "#008300", "#4a3aa7"],
        neutral="#b5b3ab",
    ),
    "dark": dict(
        surface="#1a1a19", page="#0d0d0d", ink="#ffffff", ink2="#c3c2b7", muted="#898781",
        grid="#2c2c2a", axis="#383835", warn="#e66767",
        series=["#3987e5", "#d95926", "#199e70", "#c98500", "#d55181", "#008300", "#9085e9"],
        neutral="#5f5e5a",
    ),
}

STAMP = "MicroScout · Gate G3 draft · DRAFT – UNVERIFIED · estimates and datasheet values, not measurements"

plt.rcParams.update({
    "font.family": "DejaVu Sans",
    "font.size": 10,
    "axes.titlesize": 13,
    "axes.titleweight": "bold",
    "svg.fonttype": "path",       # text as outlines: renders identically everywhere (GitHub has no DejaVu)
    "svg.hashsalt": "microscout",  # deterministic SVG ids
})


def load_budgets():
    path = REPO / "review" / "G1" / "calc" / "budgets.py"
    spec = importlib.util.spec_from_file_location("budgets", path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def read_csv_rows(path):
    lines = [l for l in pathlib.Path(path).read_text().splitlines() if l and not l.startswith("#")]
    return list(csv.DictReader(lines))


def style_axes(ax, t, grid_axis="x"):
    ax.set_facecolor(t["surface"])
    for side in ("top", "right"):
        ax.spines[side].set_visible(False)
    for side in ("left", "bottom"):
        ax.spines[side].set_color(t["axis"])
        ax.spines[side].set_linewidth(0.8)
    ax.tick_params(colors=t["muted"], labelcolor=t["ink2"], length=0, labelsize=9)
    ax.grid(axis=grid_axis, color=t["grid"], linewidth=0.8, linestyle="-")
    ax.set_axisbelow(True)
    ax.xaxis.label.set_color(t["ink2"])
    ax.yaxis.label.set_color(t["ink2"])


def new_fig(t, w, h):
    fig = plt.figure(figsize=(w, h), dpi=100)
    fig.patch.set_facecolor(t["surface"])
    return fig


def title_block(fig, t, title, subtitle, x=0.035, y=0.955):
    fig.text(x, y, title, color=t["ink"], fontsize=14, fontweight="bold", va="top")
    fig.text(x, y - 0.065, subtitle, color=t["ink2"], fontsize=9.5, va="top", wrap=True)


def stamp(fig, t, extra=""):
    text = STAMP + (f" · {extra}" if extra else "")
    fig.text(0.035, 0.018, text, color=t["muted"], fontsize=7.5, va="bottom")


def save_svg(fig, name, theme):
    FIG_DIR.mkdir(parents=True, exist_ok=True)
    out = FIG_DIR / f"{name}-{theme}.svg"
    fig.savefig(out, format="svg", facecolor=fig.get_facecolor(), metadata={"Date": None})
    plt.close(fig)
    txt = out.read_text()
    header = "<!-- STATUS: DRAFT - UNVERIFIED - requires human review at Gate G2 (generated by tools/viz; do not hand-edit) -->\n"
    if "STATUS: DRAFT" not in txt[:400]:
        first_nl = txt.index("\n") + 1  # after <?xml ...?>
        txt = txt[:first_nl] + header + txt[first_nl:]
    out.write_text(txt)
    return out
