# STATUS: DRAFT - UNVERIFIED - requires human review at Gate G2
"""Generate review/G2/pullups-straps.md from the schematic sources (every pull resistor, the
ESP32-S3 strapping pins and the other boot-sensitive pins). Licence: MIT."""
import importlib.util
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
REPO = HERE.parents[1]
sys.path.insert(0, str(HERE))

SUPPLIES = {"+3V3", "+5V", "VLOGIC", "VBAT", "VDRV", "+3V3_ESC", "CHG_REGN", "+2V8", "+1V2"}
DESIGNS = [("Flight controller", REPO / "hardware/drone-pcb/design/fc.py", 0),
           ("ESC (motor 1 shown; motors 2-4 identical)", REPO / "hardware/esc-pcb/design/esc.py", 0),
           ("ToF side satellite", REPO / "hardware/tof-satellites/design/tof.py", 0),
           ("ToF front satellite", REPO / "hardware/tof-satellites/design/tof.py", 1)]

STRAPS = [
    ("GPIO0", "BOOT_N", "R31 10 k to 3V3 + BOOT button to GND", "1 = SPI boot (normal); 0 with GPIO46 = 0 = download mode",
     "High at reset unless BOOT is held. No capacitor on the pin (Espressif checklist)."),
    ("GPIO3", "EXP_INT_N", "R32 10 k to 3V3; open-drain sources only (2x TCA6408A INT, INA226 ALERT)",
     "JTAG source select, read only if the STRAP_JTAG_SEL eFuse is burned", "Never burn that eFuse. The open-drain sources cannot drive it high or low at reset except by pulling low if an interrupt is pending - harmless while the eFuse is not burned."),
    ("GPIO45", "LED_DIN_3V3", "R33 10 k to GND; drives only the SN74AHCT1G125 input (high impedance)",
     "0 = 3.3 V flash/PSRAM supply (required for N8R2)", "Must be 0 at reset - held low by R33 and the module's weak pull-down."),
    ("GPIO46", "BUZZER", "R60 100 k to GND at the Q3 gate", "0 required for download mode with GPIO0 = 0; also ROM log routing",
     "Low at reset; FET off, buzzer silent."),
]


def load(path):
    spec = importlib.util.spec_from_file_location(path.stem + "_sum", path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def pulls(project, only_suffix=None):
    out = []
    for p in sorted(project.parts.values(), key=lambda x: x.ref):
        if p.lib_id != "Device:R":
            continue
        a, b = p.netmap["1"], p.netmap["2"]
        for sig, rail in ((a, b), (b, a)):
            if rail in SUPPLIES and sig not in SUPPLIES and sig != "GND":
                out.append((sig, "up", rail, p.ref, p.value))
            elif rail == "GND" and sig not in SUPPLIES and sig != "GND":
                out.append((sig, "down", rail, p.ref, p.value))
    if only_suffix:
        out = [o for o in out if not o[0].startswith("M") or o[0].startswith(only_suffix)]
    return out


def main():
    L = ["> STATUS: DRAFT - UNVERIFIED - requires human review at Gate G2", "",
         "# Pull-ups, pull-downs and strapping pins (G2)", "",
         "Generated by `tools/sch/summaries.py` from the schematic sources. A resistor counts as a pull when one end is a",
         "supply or GND and the other a signal. Dividers and filters also appear (noted).", ""]
    L += ["## ESP32-S3 strapping pins", "", "| Pin | Net | Circuit | Meaning at reset | Level at reset (design intent) |", "|---|---|---|---|---|"]
    for row in STRAPS:
        L.append("| " + " | ".join(row) + " |")
    L += ["", "Other boot-sensitive lines:", "",
          "- **DShot outputs GPIO2/21/38/47:** 100 k pull-downs (R34-R37) hold the lines low while the ESP32 resets, so the ESCs see no frames (DR-03). Bidirectional DShot idles high once running; whether AM32 accepts a low line at its own boot is a G6 check.",
          "- **SPI chip selects:** IMU_CS_N (R52) and FLOW_CS_N (R56) pulled up so both sensors are deselected during boot.",
          "- **EN (reset):** R30 10 k + C33 1 uF (Espressif RC). **PWR_KILL_N:** R14 100 k up holds the board on; GPIO48 or U23 pull it low to power off.",
          "- **AT32F421 (each ESC MCU):** BOOT0 10 k to GND (boot from flash); NRST has 100 nF to GND and the chip's internal pull-up.",
          "- **TCA6408A:** RESET pulled up (R53); all expander pins start as inputs, so the outside pulls set the safe state.", ""]
    for title, path, idx in DESIGNS:
        projects = load(path).build()
        proj = projects[idx] if isinstance(projects, list) else projects
        rows = pulls(proj, only_suffix="M1_" if "ESC" in title else None)
        L += [f"## {title}", "", "| Net | Pull | To | Ref | Value |", "|---|---|---|---|---|"]
        for sig, d, rail, ref, val in sorted(rows):
            L.append(f"| {sig} | {d} | {rail} | {ref} | {val} |")
        L.append("")
    (REPO / "review" / "G2" / "pullups-straps.md").write_text("\n".join(L) + "\n")
    print("wrote review/G2/pullups-straps.md")


if __name__ == "__main__":
    main()
