# STATUS: DRAFT - UNVERIFIED - requires human review at Gate G3
# SPDX-License-Identifier: MIT
"""Copper width for the high-current paths (writes review/G3/trace-widths.md).

Method: the IPC-2221 conductor formula I = k * dT^0.44 * A^0.725 (A in mil^2; k = 0.048 outer,
0.024 inner). IPC-2152 replaced it with charts that usually allow *narrower* internal conductors; the
charts themselves are not reproduced here, so the IPC-2221 result is used as the conservative bound and
labelled as such. Short paths (a few mm) run cooler than these long-conductor numbers because the pads,
parts and planes sink heat; that benefit is not counted.
"""
import pathlib

REPO = pathlib.Path(__file__).resolve().parents[2]
MIL = 0.0254
OZ_UM = {1.0: 35.0, 0.5: 17.5, 2.0: 70.0}
# FC: 1 oz outer / 0.5 oz inner (JLC default, UNCONFIRMED). ESC: 2 oz outer / 1 oz inner, as in the G1 mass budget
# (budgets.py, ASSUMPTION) - the ESC stackup must be ordered that way or these widths double.


def width_mm(I, dT, oz, external=True):
    k = 0.048 if external else 0.024
    area_mil2 = (I / (k * dT ** 0.44)) ** (1 / 0.725)
    t_mil = OZ_UM[oz] / 1000 / MIL
    return area_mil2 / t_mil * MIL


PATHS = [
    # (name, current A, note, layers available as [(oz, external)])
    ("FC battery path J2 -> RS1 -> J8 (VBAT_RAW, VBAT)", 30.0, "firmware current limit DR-06; 37.7 A full-throttle estimate (budgets 3d); islands on L1, L3, L4, L6",
     [(1.0, True), (0.5, False), (0.5, False), (1.0, True)]),
    ("FC ground return J2 -> J9", 30.0, "same current; GND on L1, L2, L3, L5 and L6 (L4 carries the +3V3 pour)",
     [(1.0, True), (0.5, False), (0.5, False), (0.5, False), (1.0, True)]),
    ("ESC VBAT feed J2 -> four half-bridge groups", 30.0, "In2 VBAT plane plus the top VBAT pour", [(1.0, False), (2.0, True)]),
    ("ESC one motor phase (FETs -> motor pad)", 9.2, "EX1103 vendor table: 9.2 A at full throttle on 7.4 V (S15)", [(2.0, True)]),
    ("ESC one half-bridge VBAT/GND (per FET pair)", 9.2, "", [(2.0, True), (1.0, False)]),
]


def main():
    out = [
        "> STATUS: DRAFT - UNVERIFIED - requires human review at Gate G3",
        "",
        "# High-current copper (G3)",
        "",
        "Generated by `tools/pcb/currents.py`. **Method:** the IPC-2221 conductor formula `I = k * dT^0.44 * A^0.725` "
        "(A in square mils; k = 0.048 for outer layers, 0.024 for inner layers). IPC-2152 replaced this with charts that usually "
        "allow narrower internal conductors; the charts are not reproduced here, so these numbers are a **conservative bound**, "
        "not an IPC-2152 result. Copper assumed: flight controller (6 layers, D-062) 1 oz (35 um) outer and 0.5 oz (17.5 um) inner; ESC 2 oz (70 um) outer and 1 oz inner, as the G1 mass budget assumes. Both are UNCONFIRMED "
        "until the G4 stackup is chosen; ordering the ESC in 1 oz would roughly double the ESC widths below.",
        "",
        "Worked example (first row, 20 C, outer layer): A = (I / (k dT^0.44))^(1/0.725); the four layers share the current, "
        "so the solver finds the one width w at which the four cross-sections together carry 30 A.",
        "",
        "| Path | Current | Note | Width needed for a 20 C rise | for a 40 C rise |",
        "|---|---:|---|---|---|",
    ]
    for name, I, note, layers in PATHS:
        def total(dT):
            # parallel layers share current in proportion to their cross-section: solve for the common width
            lo, hi = 0.01, 200.0
            for _ in range(60):
                w = (lo + hi) / 2
                cap = sum(I_of(w, dT, oz, ext) for oz, ext in layers)
                lo, hi = (w, hi) if cap < I else (lo, w)
            return hi

        def I_of(w, dT, oz, ext):
            k = 0.048 if ext else 0.024
            area = (w / MIL) * (OZ_UM[oz] / 1000 / MIL)
            return k * dT ** 0.44 * area ** 0.725
        lay = " + ".join(f"{oz:g} oz {'outer' if ext else 'inner'}" for oz, ext in layers)
        out.append(f"| {name} | {I:g} A | {note} | {total(20):.1f} mm on each of {lay} | {total(40):.1f} mm |")
    out += [
        "",
        "What the layout does about it is listed in `review/G3/README.md` (copper actually drawn per path, measured from the "
        "board files). **The 30 A battery path is the weak point.** The widths above are for a long conductor in still air. "
        "The flight-controller path is not long: the battery pigtail pads, the shunt and the ESC wire pads sit side by side, and "
        "the copper between them is a solid island on L1, L3, L4 and L6 joined by stitching vias, wider than the IPC-2221 bound "
        "only where the parts leave room. Whether that is cool enough is UNCONFIRMED: the temperature rise must be measured "
        "at G6 (bench, props off, electronic load, thermocouple on the shunt) before any full-throttle flight.",
    ]
    p = REPO / "review/G3/trace-widths.md"
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text("\n".join(out) + "\n")
    print("wrote", p.relative_to(REPO))


if __name__ == "__main__":
    main()
